[package]
name = "dawnjection"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
axum = ["dep:axum"]
rocket = ["dep:rocket"]

[dependencies]
dawnjection-codegen ={ path = "../core-codegen" }
async-trait = "0.1.81"
eyre = "0.6.8"
futures = "0.3.28"

rocket = { version="0.5", optional = true }
axum = { version = "0.6", optional = true }
# tokio = { version = "1", features = ["full"], optional = true }

[dev-dependencies]
tokio = {version="*", features = ["full"]}
color-eyre = "*"

[[example]]
name = "axum"
path = "examples/axum.rs"
required-features = ["axum"]
[[example]]
name = "rocket"
path = "examples/rocket.rs"
required-features = ["rocket"]
